name: flake8 Lint

on:
  pull_request:
    paths:
      - "*.py"
  push:
    paths:
      - "*.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 lint

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install mypy
        run: pip install mypy

      - name: flake8 lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "90"

      - name: Run mypy
        run: |
          mypy \
            --install-types \
            --non-interactive \
            --ignore-missing-imports \
            --check-untyped-defs \
            --disallow-untyped-defs \
            --allow-redefinition \
            --follow-imports=skip \
            $CHANGED_FILES


